import React, { useMemo, useState } from 'react';
import { AppScreen, GenerationTask, ProductAsset, TaskStatus, VideoTaskEntryContext } from '../types';
import { TaskDetailsDrawer } from './TaskDetailsDrawer';

interface TaskListProps {
  tasks: GenerationTask[];
  products: ProductAsset[];
  onAddTask: (task: GenerationTask) => void;
  onUpdateTask: (task: GenerationTask) => void;
  setScreen: (screen: AppScreen) => void;
  onCreateVideo: (context: VideoTaskEntryContext | GenerationTask) => void;
}

const STATUS_META: Record<TaskStatus, { label: string; style: string }> = {
  pending: { label: '待生成', style: 'bg-slate-100 text-slate-600' }, running: { label: '生成中', style: 'bg-blue-50 text-primary' }, completed: { label: '已完成', style: 'bg-slate-100 text-slate-600' }, failed: { label: '生成失败', style: 'bg-red-50 text-red-700' }, rejected: { label: '已打回', style: 'bg-red-50 text-red-700' }, candidate: { label: '待评分审核', style: 'bg-slate-100 text-slate-600' }, aesthetic_review: { label: '待评分审核', style: 'bg-slate-100 text-slate-600' }, listing_review: { label: '待评分审核', style: 'bg-slate-100 text-slate-600' }, archived: { label: '审核通过', style: 'bg-emerald-50 text-emerald-700' }, cancelled: { label: '已取消', style: 'bg-slate-200 text-slate-500' },
};

export const TaskList: React.FC<TaskListProps> = ({ tasks, products, onAddTask, onUpdateTask, setScreen, onCreateVideo }) => {
  const [kind, setKind] = useState<'image' | 'video'>('image');
  const [status, setStatus] = useState<'all' | TaskStatus>('all');
  const [query, setQuery] = useState('');
  const [selectedTask, setSelectedTask] = useState<GenerationTask | null>(null);
  const [tab, setTab] = useState<'overview' | 'inputs' | 'results' | 'reviews' | 'costs'>('overview');
  const visible = useMemo(() => tasks.filter((task) => task.type === kind && (status === 'all' || task.status === status) && `${task.name}${task.id}${task.productName}`.toLowerCase().includes(query.toLowerCase())), [kind, query, status, tasks]);
  const updateRunning = (task: GenerationTask) => {
    const next = { ...task, status: 'running' as const, progress: 0, errorMsg: undefined };
    onUpdateTask(next);
    window.setTimeout(() => onUpdateTask({ ...next, status: 'candidate', progress: 100, resultUrl: task.productImg, results: [{ id: `${task.id}-retry-${Date.now()}`, url: task.productImg, version: 1, reviewStage: 'candidate' }] }), 900);
  };
  const statusTabs: Array<'all' | TaskStatus> = ['all', 'running', 'candidate', 'archived', 'failed', 'rejected'];
  return <div className="space-y-5">
    <div className="flex flex-col md:flex-row md:items-end justify-between gap-4"><div><p className="text-xs font-bold text-primary">生成与评分审核闭环</p><h2 className="text-2xl font-black text-slate-900 mt-1">任务列表</h2><p className="mt-2 text-sm text-slate-500">每种图片类型都是独立任务，评分审核一次完成：通过可创建视频，打回可继续修改。</p></div><div className="flex gap-2"><button onClick={() => setScreen(AppScreen.CREATE_IMAGE_TASK)} className="h-9 px-4 rounded-md bg-primary text-white text-xs font-bold">新建图片任务</button><button onClick={() => setScreen(AppScreen.CREATE_VIDEO_TASK)} className="h-9 px-4 rounded-md border border-slate-200 bg-white text-slate-700 text-xs font-bold">新建视频任务</button></div></div>
    <div className="bg-white rounded-lg border border-slate-200 p-2 flex gap-2"><button onClick={() => { setKind('image'); setStatus('all'); }} className={`h-9 px-4 rounded-md text-xs font-bold ${kind === 'image' ? 'bg-slate-900 text-white' : 'text-slate-500'}`}>图片任务 ({tasks.filter((task) => task.type === 'image').length})</button><button onClick={() => { setKind('video'); setStatus('all'); }} className={`h-9 px-4 rounded-md text-xs font-bold ${kind === 'video' ? 'bg-slate-900 text-white' : 'text-slate-500'}`}>视频任务 ({tasks.filter((task) => task.type === 'video').length})</button></div>
    <div className="bg-white rounded-lg border border-slate-200 p-4 flex flex-col lg:flex-row gap-3 lg:items-center justify-between"><div className="flex flex-wrap gap-2">{statusTabs.map((item) => { const meta = item === 'all' ? { label: '全部', style: '' } : STATUS_META[item]; const count = tasks.filter((task) => task.type === kind && (item === 'all' || task.status === item)).length; return <button key={item} onClick={() => setStatus(item)} className={`h-8 px-3 rounded-md text-xs font-bold ${status === item ? 'bg-primary text-white' : 'bg-slate-50 text-slate-500 hover:bg-slate-100'}`}>{meta.label} {count}</button>; })}</div><div className="relative"><span className="material-symbols-outlined absolute left-2.5 top-2 text-slate-400 text-base">search</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="搜索任务、商品或编号" className="h-9 w-60 pl-8 pr-3 rounded-md border border-slate-200 text-xs" /></div></div>
    <div className="bg-white rounded-lg border border-slate-200 overflow-hidden"><div className="overflow-x-auto"><table className="w-full min-w-[960px] text-left"><thead className="bg-slate-50 text-[11px] text-slate-500"><tr><th className="p-4 font-bold">任务</th><th className="p-4 font-bold">商品与图片类型</th><th className="p-4 font-bold">任务组 / 模板</th><th className="p-4 font-bold">模型与业务规格</th><th className="p-4 font-bold">状态</th><th className="p-4 font-bold text-right">操作</th></tr></thead><tbody className="divide-y divide-slate-100">{visible.map((task) => { const meta = STATUS_META[task.status]; const typeLabel = task.imageType ? ({ product_main: '商品主图', scene_detail: '详情/场景图', detail_closeup: '细节图', on_model: '上身/三视图' }[task.imageType]) : task.type === 'video' ? '受控视频' : '图片任务'; return <tr key={task.id} className="hover:bg-slate-50/70"><td className="p-4"><p className="text-[10px] text-slate-400 font-mono">{task.id}</p><p className="mt-1 text-xs font-black text-slate-800 max-w-[220px]">{task.name}</p></td><td className="p-4"><div className="flex gap-2 items-center"><img src={task.productImg} alt="" className="w-9 h-9 rounded object-cover" referrerPolicy="no-referrer"/><div><p className="text-xs font-bold">{task.productName}</p><p className="mt-1 text-[10px] text-slate-400">{typeLabel}</p></div></div></td><td className="p-4"><p className="text-xs font-bold">{task.templateName}</p><p className="mt-1 text-[10px] text-slate-400">{task.groupId ? `任务组 ${task.groupId}` : '独立任务'}</p></td><td className="p-4"><p className="text-xs font-bold max-w-[190px] truncate">{task.modelSnapshot?.modelName ?? task.modelChannel}</p><p className="mt-1 text-[10px] text-slate-400">{task.params?.ratio ?? '—'} · {task.modelSnapshot?.estimatedCost?.toFixed(1) ?? '—'} 元</p></td><td className="p-4"><span className={`px-2 py-1 rounded text-[10px] font-bold ${meta.style}`}>{meta.label}</span>{task.status === 'running' && <div className="mt-2 h-1 w-24 rounded bg-slate-100 overflow-hidden"><div className="h-full bg-primary" style={{ width: `${task.progress}%` }} /></div>}</td><td className="p-4"><div className="flex justify-end gap-2"><button onClick={() => { setTab('overview'); setSelectedTask(task); }} className="h-8 px-2.5 rounded border border-slate-200 text-xs font-bold">详情</button>{['candidate', 'completed', 'archived', 'rejected'].includes(task.status) && <button onClick={() => { setTab('results'); setSelectedTask(task); }} className="h-8 px-2.5 rounded bg-blue-50 text-primary text-xs font-bold">处理结果</button>}{task.status === 'failed' && <button onClick={() => updateRunning(task)} className="h-8 px-2.5 rounded bg-red-50 text-red-700 text-xs font-bold">重试</button>}</div></td></tr>; })}{visible.length === 0 && <tr><td colSpan={6} className="p-16 text-center text-sm text-slate-400">没有符合条件的任务</td></tr>}</tbody></table></div></div>
    {selectedTask && <TaskDetailsDrawer task={selectedTask} products={products} initialTab={tab} onClose={() => setSelectedTask(null)} onUpdateTask={(next) => { onUpdateTask(next); setSelectedTask(next); }} onAddTask={onAddTask} onCreateVideo={onCreateVideo} />}
  </div>;
};
