import { GenerationTask, AdTemplate, ProductAsset, ModelChannel, SystemUser, SystemNotification } from './types';

export const mockUsers: SystemUser[] = [
  { id: 'u1', name: '陆永奇', avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=150&q=80', role: '管理员', email: 'lu.yq@davinci.ai', status: 'online', joinedDate: '2025-01-15' },
  { id: 'u2', name: '陈美晴', avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=150&q=80', role: '高级设计师', email: 'chen.mq@davinci.ai', status: 'online', joinedDate: '2025-03-22' },
  { id: 'u3', name: '张思豪', avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80', role: '运营策划', email: 'zhang.sh@davinci.ai', status: 'offline', joinedDate: '2025-05-10' },
  { id: 'u4', name: '林若云', avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=150&q=80', role: '协同客户', email: 'client.lin@nike.com', status: 'online', joinedDate: '2026-02-18' }
];

export const mockNotifications: SystemNotification[] = [
  { id: 'n1', title: '任务生成成功', content: '「智能运动手表_夏日活力宣传图」批次生成已完成（10/10），已自动存入资源中转站。', type: 'success', time: '10 分钟前', read: false },
  { id: 'n2', title: '算力额度预警', content: '本月企业算力点数已使用 78.4%，建议及时补充以免影响批次任务。', type: 'warning', time: '1 小时前', read: false },
  { id: 'n3', title: '任务生成失败', content: '「极地防寒羽绒服_动态飞雪场景短视频」由于底图复杂度过高导致渲染超时（Error Code: 504）。', type: 'error', time: '2 小时前', read: true },
  { id: 'n4', title: '新模板审核提醒', content: '设计师 陈美晴 提交了「3D极简展示模板」待审核发布。', type: 'info', time: '1 天前', read: true }
];

export const mockModelChannels: ModelChannel[] = [
  { id: 'm1', name: 'DaVinci Vision v3.5 (自研推荐)', provider: 'DaVinci Core', status: 'active', todayUsage: 1420, limit: 5000, latency: '1.2s' },
  { id: 'm2', name: 'Midjourney v6.1 High-Res Proxy', provider: 'Midjourney', status: 'active', todayUsage: 890, limit: 2000, latency: '4.5s' },
  { id: 'm3', name: 'Stable Diffusion 3.5 Large Inpaint', provider: 'Stable Diffusion', status: 'active', todayUsage: 350, limit: 3000, latency: '1.8s' },
  { id: 'm4', name: 'Runway Gen-3 Alpha Video API', provider: 'Runway', status: 'active', todayUsage: 120, limit: 500, latency: '8.2s' },
  { id: 'm5', name: 'Kling AI 1.5 Pro Video Engine', provider: 'Kling AI', status: 'inactive', todayUsage: 0, limit: 500, latency: 'N/A' }
];

export const mockTemplates: AdTemplate[] = [
  {
    id: 't_white',
    title: '女装电商白底图 V2',
    type: 'image',
    category: '电商主图',
    ratio: '3:4',
    usedCount: 12400,
    status: 'active',
    modifier: '陈美晴',
    updatedTime: '2026-07-04 10:24',
    previewUrl: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=500&q=80',
    promptTemplate: 'Professional studio photography of a female model wearing {{product_name}}, {{category}}, pure white background, bright studio lighting, soft shadows, front view, high fashion editorial style, 8k, ultra-detailed.',
    tabCategory: 'image_task',
    taskType: '商品生图',
    applicableCategory: '女装/外套',
    defaultStyle: '简约白底',
    defaultCount: '4张',
    defaultChannel: 'Midjourney v6',
    version: 'v2.1.0',
    avgAestheticScore: 8.5,
    approvalRate: '94%',
    negativePrompt: 'bad anatomy, worst quality, low resolution, blurry',
    imageTaskType: '主图',
    variableFields: ['商品名', '颜色', '面料', '卖点'],
    relatedNegativeConstraints: ['高精度手部与面部保真约束']
  },
  {
    id: 't1',
    title: '3D 赛博虚拟炫彩展示架',
    type: 'image',
    category: '电商主图',
    ratio: '1:1',
    usedCount: 1420,
    status: 'active',
    modifier: '陈美晴',
    updatedTime: '2026-07-02 18:30',
    previewUrl: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=500&q=80',
    promptTemplate: 'High-end 3D cyberpunk holographic floating platform, neon glowing grid background, detailed realistic product mockup, studio lighting, highly intricate details',
    tabCategory: 'image_task',
    taskType: '商品生图',
    applicableCategory: '数码3C/鞋包',
    defaultStyle: '赛博炫彩',
    defaultCount: '4张',
    defaultChannel: 'DaVinci Vision',
    version: 'v1.5.0',
    avgAestheticScore: 8.3,
    approvalRate: '90%',
    imageTaskType: '细节图',
    variableFields: ['商品主体', '霓虹色泽'],
    relatedNegativeConstraints: ['物理结构防畸变规约']
  },
  {
    id: 't2',
    title: '极简北欧冷淡风大理石',
    type: 'image',
    category: '场景融合',
    ratio: '3:4',
    usedCount: 950,
    status: 'active',
    modifier: '陆永奇',
    updatedTime: '2026-07-01 11:20',
    previewUrl: 'https://images.unsplash.com/photo-1608248597481-496100c8c836?auto=format&fit=crop&w=500&q=80',
    promptTemplate: 'Minimalist Nordic display stone podium, elegant white marble texture, warm morning sunlight shadow cast, beige clean sand plaster background, architectural depth',
    tabCategory: 'style_scene',
    taskType: '场景融合',
    applicableCategory: '美妆护肤',
    defaultStyle: '北欧简约',
    defaultCount: '2张',
    defaultChannel: 'Stable Diffusion XL',
    version: 'v1.2.0',
    avgAestheticScore: 8.4,
    approvalRate: '92%',
    styleType: '场景',
    styleTags: ['极简北欧', '冷淡艺术'],
    sceneTags: ['精致大理石台', '晨曦日照侧影'],
    poseTags: ['静物俯仰视角']
  },
  {
    id: 't3',
    title: '盛夏户外阳光与椰影沙滩',
    type: 'image',
    category: '场景融合',
    ratio: '16:9',
    usedCount: 720,
    status: 'active',
    modifier: '陈美晴',
    updatedTime: '2026-06-28 09:40',
    previewUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=500&q=80',
    promptTemplate: 'Sunny bright summer resort beach background, soft white sand, tropical palm trees shadows, clear turquoise sea waves water caressing product container',
    tabCategory: 'style_scene',
    taskType: '场景融合',
    applicableCategory: '美妆/配饰',
    defaultStyle: '盛夏沙滩',
    defaultCount: '4张',
    defaultChannel: 'Midjourney v6',
    version: 'v1.0.0',
    avgAestheticScore: 8.1,
    approvalRate: '86%',
    styleType: '风格',
    styleTags: ['盛夏海滨', '热带风情'],
    sceneTags: ['细白椰林沙滩', '碧蓝微风海浪'],
    poseTags: ['自然平视视角']
  },
  {
    id: 't4',
    title: '动态爆破能量粒子环绕视频',
    type: 'video',
    category: '短视频脚本',
    ratio: '9:16',
    usedCount: 380,
    status: 'active',
    modifier: '张思豪',
    updatedTime: '2026-07-02 15:45',
    previewUrl: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=500&q=80',
    promptTemplate: 'Cinematic 3D slow-motion panning of product, exploding glowing neon energy shockwaves, flying micro tech particles, hyper realistic rendering, Unreal Engine 5 aesthetic',
    tabCategory: 'video_prompt',
    taskType: '视频脚本',
    applicableCategory: '数码3C',
    defaultStyle: '科技爆破',
    defaultCount: '1个',
    defaultChannel: 'Runway Gen-3',
    version: 'v1.1.0',
    avgAestheticScore: 8.2,
    approvalRate: '88%',
    videoMode: 'img2video',
    applicableImageTypes: ['数码3C主图', '科技氛围渲染图'],
    defaultDuration: '8s',
    motionRange: 'large',
    threeStageStructure: {
      opening: '科技硬件主体静止于中心，蓝色环形灯缓慢呼吸闪烁',
      dynamic: '镜头突然大范围横向移动，两侧升腾出炫彩电荷爆破粒子流',
      detailEnding: '镜头慢动作推近，极速聚焦至精细防滑表盘与钛金属按键收束'
    },
    negativePrompt: 'blurry background, severe ghosting, violent frame shaking, extreme drift'
  },
  {
    id: 't5',
    title: '高奢丝绸缎面优雅漂浮场景',
    type: 'image',
    category: '场景融合',
    ratio: '1:1',
    usedCount: 1280,
    status: 'active',
    modifier: '陈美晴',
    updatedTime: '2026-07-01 16:15',
    previewUrl: 'https://images.unsplash.com/photo-1518531933037-91b2f5f229cc?auto=format&fit=crop&w=500&q=80',
    promptTemplate: 'Elegant silk satin drapery floating in zero gravity, soft gold champagne color tone, ambient warm product backlighting, luxury catalog editorial atmosphere',
    tabCategory: 'style_scene',
    taskType: '场景融合',
    applicableCategory: '服饰/箱包',
    defaultStyle: '优雅丝绸',
    defaultCount: '4张',
    defaultChannel: 'Stable Diffusion XL',
    version: 'v2.0.0',
    avgAestheticScore: 8.8,
    approvalRate: '95%',
    styleType: '组合预设',
    styleTags: ['优雅奢华', '古典香槟金'],
    sceneTags: ['失重悬浮香槟缎面', '柔焦背光光辉'],
    poseTags: ['丝滑流线褶皱']
  },
  {
    id: 't6',
    title: '冬季风雪覆盖深色岩石展示',
    type: 'image',
    category: '场景融合',
    ratio: '4:3',
    usedCount: 420,
    status: 'active',
    modifier: '陆永奇',
    updatedTime: '2026-07-03 08:10',
    previewUrl: 'https://images.unsplash.com/photo-1483168527879-c66136b56105?auto=format&fit=crop&w=500&q=80',
    promptTemplate: 'Cinematic cold dark mountain wet slate rocks covered with crisp powder snow, heavy dense winter blizzard particles, dramatic blue hour lighting, cold temperature',
    tabCategory: 'style_scene',
    taskType: '场景融合',
    applicableCategory: '通用',
    defaultStyle: '冬季风雪',
    defaultCount: '2张',
    defaultChannel: 'Stable Diffusion XL',
    version: 'v1.0.0',
    avgAestheticScore: 8.0,
    approvalRate: '85%',
    styleType: '场景',
    styleTags: ['寒冬冰冷电影感', '冷郁硬核'],
    sceneTags: ['落雪玄武岩山脉', '高密度飞雪颗粒'],
    poseTags: ['俯角广角透视']
  },
  {
    id: 't_spec1',
    title: '小红书种草 3:4 爆款图规范',
    type: 'image',
    category: '电商主图',
    ratio: '3:4',
    usedCount: 8900,
    status: 'active',
    modifier: '陆永奇',
    updatedTime: '2026-07-02 11:20',
    previewUrl: 'https://images.unsplash.com/photo-1518531933037-91b2f5f229cc?auto=format&fit=crop&w=500&q=80',
    promptTemplate: 'Instagram/Xiaohongshu style aesthetic layout, optimal typography contrast, safe zone compliance for social media commerce',
    tabCategory: 'platform_spec',
    taskType: '规格排版',
    applicableCategory: '通用',
    defaultStyle: '小红书规范',
    defaultCount: '1张',
    defaultChannel: 'DaVinci Vision',
    version: 'v1.1.0',
    avgAestheticScore: 8.9,
    approvalRate: '96%',
    specUsage: '详情页场景图',
    specMaterialType: '图片',
    specWidth: 1242,
    specHeight: 1660,
    specFormat: 'webp',
    maxFileSize: '3MB',
    isDefaultRecommended: true
  },
  {
    id: 't_spec2',
    title: '淘宝首图 1:1 直通车规范',
    type: 'image',
    category: '电商主图',
    ratio: '1:1',
    usedCount: 15600,
    status: 'active',
    modifier: '陈美晴',
    updatedTime: '2026-07-01 14:30',
    previewUrl: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=500&q=80',
    promptTemplate: 'E-commerce main banner safe zone ratio 1:1, high conversion CTR layout text overlay compliance template',
    tabCategory: 'platform_spec',
    taskType: '规格排版',
    applicableCategory: '通用',
    defaultStyle: '直通车规范',
    defaultCount: '2张',
    defaultChannel: 'DaVinci Vision',
    version: 'v2.0.0',
    avgAestheticScore: 8.7,
    approvalRate: '98%',
    specUsage: '商品主图',
    specMaterialType: '图片',
    specWidth: 800,
    specHeight: 800,
    specFormat: 'jpg',
    maxFileSize: '1MB',
    isDefaultRecommended: true
  },
  {
    id: 't_neg1',
    title: '高精度手部与面部保真约束',
    type: 'image',
    category: '场景融合',
    ratio: 'N/A',
    usedCount: 22000,
    status: 'active',
    modifier: '陈美晴',
    updatedTime: '2026-07-03 09:12',
    previewUrl: 'https://images.unsplash.com/photo-1608248597481-496100c8c836?auto=format&fit=crop&w=500&q=80',
    promptTemplate: 'bad anatomy, deformed fingers, extra limbs, bad face structure, fused hands, low quality textures',
    tabCategory: 'negative_constraint',
    taskType: '负面提示',
    applicableCategory: '通用/服饰模特',
    defaultStyle: '高保真约束',
    defaultCount: 'N/A',
    defaultChannel: 'Stable Diffusion',
    version: 'v3.0.0',
    avgAestheticScore: 9.1,
    approvalRate: '99%',
    applicableMaterialTypes: '通用',
    constraintCategory: '人物人体',
    severityLevel: 'P0',
    chineseDescription: '防止肢体、手指产生异常扭曲和人脸融化现象，强力在底层控制画质防垮。',
    referencedTemplatesCount: 42
  },
  {
    id: 't_neg2',
    title: '老旧 3D 渲染模板 (负面避坑)',
    type: 'image',
    category: '场景融合',
    ratio: '1:1',
    usedCount: 3200,
    status: 'draft',
    modifier: '陆永奇',
    updatedTime: '2026-01-12 11:00',
    previewUrl: 'https://images.unsplash.com/photo-1483168527879-c66136b56105?auto=format&fit=crop&w=500&q=80',
    promptTemplate: 'bad quality, plastic feel, low detail, ugly render, blurred background',
    tabCategory: 'negative_constraint',
    taskType: '负面提示',
    applicableCategory: '数码3C',
    defaultStyle: '避坑材质',
    defaultCount: '2张',
    defaultChannel: 'Stable Diffusion XL',
    version: 'v1.0.0',
    avgAestheticScore: 6.2,
    approvalRate: '45%',
    applicableMaterialTypes: '图片',
    constraintCategory: '画面质量',
    severityLevel: 'P1',
    chineseDescription: '规避过时 3D 粗糙塑料建模及廉价渲染风格，维持真实高端产品质感。',
    referencedTemplatesCount: 15
  }
];

export const mockProducts: ProductAsset[] = [
  {
    id: 'p1',
    name: 'MW Series 7 智联运动手表',
    sku: 'SKU-MW7-BLK',
    category: '智能硬件',
    imageCount: 12,
    videoCount: 3,
    thumbnail: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=500&q=80',
    addedTime: '2026-06-15',
    specs: {
      brand: 'MatrixWear',
      color: ['曜石黑', '极光银', '深海蓝'],
      material: '航天级钛金属 + 氟橡胶表带',
      weight: '48.5g',
      sellingPoints: ['双频多星GPS定位', '14天极致续航', '动态血氧/心率深度监测', '50米专业防水']
    },
    files: [
      { id: 'f1_1', name: '手表主体_正面免抠.png', url: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=400&q=80', size: '2.4 MB', type: 'image' },
      { id: 'f1_2', name: '手表右侧按键微距.png', url: 'https://images.unsplash.com/photo-1542496658-e33a6d0d50f6?auto=format&fit=crop&w=400&q=80', size: '4.1 MB', type: 'image' },
      { id: 'f1_3', name: '钛金属表盘拉丝质感.png', url: 'https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?auto=format&fit=crop&w=400&q=80', size: '3.8 MB', type: 'image' },
      { id: 'f1_4', name: '表带卡扣与人体工学.mov', url: 'https://assets.mixkit.co/videos/preview/mixkit-smartwatch-on-a-desk-close-up-34440-large.mp4', size: '28.5 MB', type: 'video' }
    ]
  },
  {
    id: 'p2',
    name: 'Nike Air Max Elite 2026 跑鞋',
    sku: 'SKU-NK-AM26-RED',
    category: '户外服饰',
    imageCount: 18,
    videoCount: 5,
    thumbnail: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=500&q=80',
    addedTime: '2026-06-20',
    specs: {
      brand: 'Nike',
      color: ['火焰红', '荧光绿', '极简白'],
      material: 'Flyknit 编织鞋面 + 氮气缓震大底',
      weight: '240g',
      sellingPoints: ['全掌蜂窝氮气气垫', '超透气编织纤维包裹', '抗扭碳纤维支撑片', '夜间反光安全涂层']
    },
    files: [
      { id: 'f2_1', name: '跑鞋免抠主图.png', url: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=400&q=80', size: '1.9 MB', type: 'image' },
      { id: 'f2_2', name: '气垫避震拉丝微距.png', url: 'https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?auto=format&fit=crop&w=400&q=80', size: '3.2 MB', type: 'image' },
      { id: 'f2_3', name: '编织鞋面特写.png', url: 'https://images.unsplash.com/photo-1600185365483-26d7a4cc7519?auto=format&fit=crop&w=400&q=80', size: '2.7 MB', type: 'image' }
    ]
  },
  {
    id: 'p3',
    name: '极致臻颜草本精华保湿乳',
    sku: 'SKU-SKN-ESS-100',
    category: '美妆护肤',
    imageCount: 8,
    videoCount: 2,
    thumbnail: 'https://images.unsplash.com/photo-1608248597481-496100c8c836?auto=format&fit=crop&w=500&q=80',
    addedTime: '2026-06-25',
    specs: {
      brand: 'PhytoGlow',
      color: ['乳白色'],
      material: '磨砂防紫外线玻璃瓶',
      weight: '100ml',
      sellingPoints: ['95% 天然草本精萃', '72小时角质层长效锁水', '清爽不粘腻配方', '敏感肌无添加安全认证']
    },
    files: [
      { id: 'f3_1', name: '精华乳白色去背.png', url: 'https://images.unsplash.com/photo-1608248597481-496100c8c836?auto=format&fit=crop&w=400&q=80', size: '1.5 MB', type: 'image' },
      { id: 'f3_2', name: '瓶盖磨砂奢华细节.png', url: 'https://images.unsplash.com/photo-1617897903246-719242758050?auto=format&fit=crop&w=400&q=80', size: '2.9 MB', type: 'image' }
    ]
  },
  {
    id: 'p4',
    name: '超轻便透气抗撕裂防风羽绒服',
    sku: 'SKU-OUT-JKT-GRY',
    category: '户外服饰',
    imageCount: 14,
    videoCount: 4,
    thumbnail: 'https://images.unsplash.com/photo-1544923246-77307dd654cb?auto=format&fit=crop&w=500&q=80',
    addedTime: '2026-06-30',
    specs: {
      brand: 'PeakTech',
      color: ['火山灰', '极夜黑', '苔原绿'],
      material: 'DWR防泼水涂层 + 800蓬松白鸭绒',
      weight: '310g',
      sellingPoints: ['极轻量可收纳设计', '防风透湿Gore-Tex结构', '抗撕裂格纹编织面料', '智能恒温蓄热里布']
    },
    files: [
      { id: 'f4_1', name: '羽绒服正面模特展示.png', url: 'https://images.unsplash.com/photo-1544923246-77307dd654cb?auto=format&fit=crop&w=400&q=80', size: '3.6 MB', type: 'image' },
      { id: 'f4_2', name: '防泼水面料荷叶效应.png', url: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=400&q=80', size: '4.2 MB', type: 'image' }
    ]
  }
];

export const mockTasks: GenerationTask[] = [
  {
    id: 'T-1004',
    name: 'Nike Air Max _ 3D赛博炫彩展示 (批次#1)',
    type: 'image',
    status: 'running',
    progress: 68,
    productName: 'Nike Air Max Elite 2026 跑鞋',
    productImg: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=150&q=80',
    templateName: '3D 赛博虚拟炫彩展示架',
    timestamp: '2026-07-03 17:42',
    creator: '陈美晴',
    modelChannel: 'DaVinci Vision v3.5 (自研推荐)',
    params: { ratio: '1:1', steps: 30, guidance: 7.5, prompt: 'Glowing neon cyan grid background, floating podium' }
  },
  {
    id: 'T-1003',
    name: '轻便防风羽绒服 _ 动态风雪覆盖 (批次#4)',
    type: 'image',
    status: 'failed',
    progress: 100,
    productName: '超轻便透气抗撕裂防风羽绒服',
    productImg: 'https://images.unsplash.com/photo-1544923246-77307dd654cb?auto=format&fit=crop&w=150&q=80',
    templateName: '冬季风雪覆盖深色岩石展示',
    timestamp: '2026-07-03 16:10',
    creator: '陆永奇',
    errorMsg: 'GPU Out of Memory (CUDA Error 2)。建议降低生成批次数量（当前为 10）或减少高保真去噪步数。',
    modelChannel: 'Stable Diffusion 3.5 Large Inpaint',
    params: { ratio: '4:3', steps: 50, guidance: 11.0 }
  },
  {
    id: 'T-1002',
    name: '精华保湿乳 _ 极简北欧大理石展示 (批次#1)',
    type: 'image',
    status: 'completed',
    progress: 100,
    productName: '极致臻颜草本精华保湿乳',
    productImg: 'https://images.unsplash.com/photo-1608248597481-496100c8c836?auto=format&fit=crop&w=150&q=80',
    templateName: '极简北欧冷淡风大理石',
    timestamp: '2026-07-03 15:30',
    creator: '陈美晴',
    resultUrl: 'https://images.unsplash.com/photo-1608248597481-496100c8c836?auto=format&fit=crop&w=600&q=80',
    modelChannel: 'DaVinci Vision v3.5 (自研推荐)',
    params: { ratio: '3:4', steps: 35, guidance: 8.0 }
  },
  {
    id: 'T-1001',
    name: 'MW Series 7 _ 能量粒子环绕动态视频 (批次#1)',
    type: 'video',
    status: 'completed',
    progress: 100,
    productName: 'MW Series 7 智联运动手表',
    productImg: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=150&q=80',
    templateName: '动态爆破能量粒子环绕视频',
    timestamp: '2026-07-03 11:15',
    creator: '张思豪',
    resultUrl: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=600&q=80',
    modelChannel: 'Runway Gen-3 Alpha Video API',
    params: { ratio: '9:16', steps: 50, guidance: 9.0 }
  },
  {
    id: 'T-1000',
    name: '精华保湿乳 _ 高奢丝绸漂浮 (批次#2)',
    type: 'image',
    status: 'rejected',
    progress: 100,
    productName: '极致臻颜草本精华保湿乳',
    productImg: 'https://images.unsplash.com/photo-1608248597481-496100c8c836?auto=format&fit=crop&w=150&q=80',
    templateName: '高奢丝绸缎面优雅漂浮场景',
    timestamp: '2026-07-02 14:05',
    creator: '陈美晴',
    feedback: '高光部分过曝，文字反差度不够，已拒绝。需要调整模型引导系数 (CFG) 到 6.5 以下，重渲染。',
    modelChannel: 'Midjourney v6.1 High-Res Proxy',
    params: { ratio: '1:1', steps: 40, guidance: 12.0 }
  },
  {
    id: 'T-0999',
    name: 'Nike Air Max 炫彩户外海报 (批次#3)',
    type: 'image',
    status: 'completed',
    progress: 100,
    productName: 'Nike Air Max Elite 2026 跑鞋',
    productImg: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=150&q=80',
    templateName: '盛夏户外阳光与椰影沙滩',
    timestamp: '2026-07-02 09:30',
    creator: '陆永奇',
    resultUrl: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=600&q=80',
    modelChannel: 'DaVinci Vision v3.5 (自研推荐)',
    params: { ratio: '16:9', steps: 30, guidance: 7.0 }
  },
  {
    id: 'T-0998',
    name: '智能运动手表概念渲染短视频 (批次#2)',
    type: 'video',
    status: 'running',
    progress: 45,
    productName: 'MW Series 7 智联运动手表',
    productImg: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=150&q=80',
    templateName: '动态爆破能量粒子环绕视频',
    timestamp: '2026-07-01 16:40',
    creator: '张思豪',
    modelChannel: 'Runway Gen-3 Alpha Video API',
    params: { ratio: '9:16', steps: 60, guidance: 8.5 }
  },
  {
    id: 'T-0997',
    name: '防风羽绒服 _ 极地探险图 (批次#1)',
    type: 'image',
    status: 'completed',
    progress: 100,
    productName: '超轻便透气抗撕裂防风羽绒服',
    productImg: 'https://images.unsplash.com/photo-1544923246-77307dd654cb?auto=format&fit=crop&w=150&q=80',
    templateName: '冬季风雪覆盖深色岩石展示',
    timestamp: '2026-07-01 10:15',
    creator: '陈美晴',
    resultUrl: 'https://images.unsplash.com/photo-1544923246-77307dd654cb?auto=format&fit=crop&w=600&q=80',
    modelChannel: 'Stable Diffusion 3.5 Large Inpaint',
    params: { ratio: '4:3', steps: 35, guidance: 8.5 }
  },
  {
    id: 'T-0996',
    name: '极致草本精华白色背景主图 (批次#1)',
    type: 'image',
    status: 'completed',
    progress: 100,
    productName: '极致臻颜草本精华保湿乳',
    productImg: 'https://images.unsplash.com/photo-1608248597481-496100c8c836?auto=format&fit=crop&w=150&q=80',
    templateName: '极简北欧冷淡风大理石',
    timestamp: '2026-06-30 14:12',
    creator: '陆永奇',
    resultUrl: 'https://images.unsplash.com/photo-1608248597481-496100c8c836?auto=format&fit=crop&w=600&q=80',
    modelChannel: 'DaVinci Vision v3.5 (自研推荐)',
    params: { ratio: '1:1', steps: 25, guidance: 6.5 }
  },
  {
    id: 'T-0995',
    name: 'Nike 跑鞋酷炫旋转飞沙视频 (批次#1)',
    type: 'video',
    status: 'completed',
    progress: 100,
    productName: 'Nike Air Max Elite 2026 跑鞋',
    productImg: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=150&q=80',
    templateName: '动态爆破能量粒子环绕视频',
    timestamp: '2026-06-29 11:00',
    creator: '张思豪',
    resultUrl: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=600&q=80',
    modelChannel: 'Kling AI 1.5 Pro Video Engine',
    params: { ratio: '16:9', steps: 80, guidance: 9.5 }
  }
];
